webdriver.driver=provided
webdriver.provided.type=classname
webdriver.provided.classname=com.browserstack.utils.SelfHealingDriverSource
webdriver.base.url=https://bstackdemo.com/

serenity.project.name=BrowserStack ScreenPlay Automation
serenity.take.screenshots=FOR_EACH_ACTION
serenity.report.show.step.details=true

# Configuracion de reportes
serenity.outputDirectory=target/site/serenity

# HealeniumSerenityListener se registra via META-INF/services (ServiceLoader)
