webdriver.driver=chrome
webdriver.base.url=https://bstackdemo.com/

serenity.project.name=BrowserStack ScreenPlay Automation
serenity.take.screenshots=FOR_EACH_ACTION
serenity.report.show.step.details=true

# Configuracion de reportes
serenity.outputDirectory=target/site/serenity
